# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 RoutineHub.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/RoutineHub.db
    volumes:
      - ./RoutineHub:/code/RoutineHub
      - ./db/:/db/
    ports:
      - "5000:5000"
