"""empty message

Revision ID: 2b39832e4c47
Revises: d59996a7e663
Create Date: 2020-02-24 20:21:32.111259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b39832e4c47'
down_revision = 'd59996a7e663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('routine', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('routine', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('routine', 'created_date')
    op.add_column('schedule', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('schedule', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('schedule', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'deleted')
    op.drop_column('user', 'created_at')
    op.drop_column('schedule', 'updated_at')
    op.drop_column('schedule', 'deleted')
    op.drop_column('schedule', 'created_at')
    op.add_column('routine', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('routine', 'updated_at')
    op.drop_column('routine', 'deleted')
    op.drop_column('routine', 'created_at')
    # ### end Alembic commands ###
