"""empty message

Revision ID: 3c04ee2b13a2
Revises: 2b39832e4c47
Create Date: 2020-02-28 11:38:52.968873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c04ee2b13a2'
down_revision = '2b39832e4c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('schedule', sa.Column('workout_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'schedule', 'workout', ['workout_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'workout_id')
    op.drop_table('workout')
    # ### end Alembic commands ###
