"""empty message

Revision ID: 48db2985e367
Revises: 6945275b3c19
Create Date: 2020-03-02 21:28:27.626601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48db2985e367'
down_revision = '6945275b3c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'schedule', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'user_id')
    # ### end Alembic commands ###
