"""empty message

Revision ID: 6945275b3c19
Revises: 3c04ee2b13a2
Create Date: 2020-02-28 13:43:29.335724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6945275b3c19'
down_revision = '3c04ee2b13a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.PickleType(), nullable=True),
    sa.Column('cadence', sa.Integer(), nullable=True),
    sa.Column('set_seconds', sa.Integer(), nullable=True),
    sa.Column('break_seconds', sa.Integer(), nullable=True),
    sa.Column('min_reps_interval', sa.Integer(), nullable=True),
    sa.Column('max_reps_interval', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_workout',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_workout')
    op.drop_table('exercise')
    # ### end Alembic commands ###
