"""empty message

Revision ID: c55fd1c97a2c
Revises: 48db2985e367
Create Date: 2020-04-12 13:46:28.361676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55fd1c97a2c'
down_revision = '48db2985e367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'routine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'routine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
